version: '3.1'

services:
  app: 
    build: .
    container_name: app_container
    depends_on: 
         - mongodb
    ports:
       - 3001:3001 
    volumes:
       - .:/app 
  
  mongodb:
    image: mongo
    container_name: mongodb_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: lappis
      MONGO_INITDB_ROOT_PASSWORD: lappis
      MONGO_INITDB_DATABASE: mongo_database 
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  metabase:
    container_name: metabase_container
    image: metabase/metabase:latest
    restart: always
    ports:
      - 3000:3000
    depends_on: 
         - postgresdb
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: lappis
      MB_DB_PORT: 5432
      MB_DB_USER: lappis
      MB_DB_PASS: lappis
      MB_DB_HOST: postgres


  postgresdb:
    image: postgres:latest
    container_name: postgresdb_container
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=lappis
      - POSTGRES_USER=lappis
      - METABASE_PASSWORD=lappis
volumes:
  mongodb_data:

# link da biblioteca publicada:  https://pypi.org/project/trabalho-individual-2022-2-kayro-cesar/0.0.1/
