version: '3.1'

services:
  app: 
    build: .
    depends_on: 
         - mongo
    ports:
       - 8000:8000 
    volumes:
      - .:/app 

  metabase:
    container_name: my-metabase
    image: metabase/metabase:latest
    ports:
      - 3000:3000
    depends_on: 
         - mongo

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: lappis
      MONGO_INITDB_ROOT_PASSWORD: lappis
    ports:
      - "27017:27017"
    volumes:
      - .:/data/db
      
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: lappis
      ME_CONFIG_MONGODB_ADMINPASSWORD: lappis
      ME_CONFIG_MONGODB_URL: mongodb://lappis:lappis@mongo:27017/ 
    volumes: 
     - .:/data